const { KINDS } = require("./catalog");

const DOC_PATH = "docs/02-protocol-catalog.md";
const README_START = "<!-- catalog:start -->";
const README_END = "<!-- catalog:end -->";

const cell = text => String(text).replace(/\|/g, "\\|");
const mark = n => (n ? (n > 1 ? `✓ ${n}` : "✓") : "");
const anchor = id => `p-${id.replace(/[^a-z0-9-]/g, "")}`;
const groupAnchor = id => `c-${id}`;
const README_PREVIEW = 6;
const link = (entry, base = "") => `[${entry.name}](${base}#${anchor(entry.id)})`;
const totalScripts = catalog => [...catalog.protocols, ...catalog.boards].reduce((n, e) => n + e.scripts.length, 0);

function grouped(catalog) {
  return catalog.categories.map(c => ({ ...c, entries: catalog.protocols.filter(p => p.category === c.id) }));
}

function commandTable(entry) {
  const rows = entry.scripts.map(s => `| \`npm run ${s.name}\` | ${s.kind} | ${cell(s.description || "")} |`);
  return ["| Command | Kind | What it does |", "|---|---|---|", ...rows].join("\n");
}

function card(entry, level) {
  const meta = [
    entry.url ? `[${entry.url.replace(/^https?:\/\/(www\.)?/, "").replace(/\/$/, "")}](${entry.url})` : null,
  ];
  if (entry.data && entry.data !== "—") meta.push(`Data: ${entry.data}`);
  meta.push(KINDS.filter(k => entry.kinds[k]).join(" · "));
  const lines = [`<a id="${anchor(entry.id)}"></a>`, "", `${"#".repeat(level)} ${entry.name}`, ""];
  lines.push(meta.filter(Boolean).join(" · "), "", entry.about, "");
  if (entry.notes?.length) {
    lines.push("> **Context**", ...entry.notes.flatMap(n => [">", `> ${n}`]), "");
  }
  lines.push(commandTable(entry), "");
  return lines.join("\n");
}

function allGroups(catalog) {
  const boards = catalog.boardGroups.map(g => ({ ...g, entries: catalog.boards.filter(b => b.group === g.id) }));
  return [...grouped(catalog), ...boards];
}

function categoryIndex(catalog, base = "", limit = Infinity) {
  const rows = allGroups(catalog).map(g => {
    const shown = g.entries.slice(0, limit).map(e => link(e, base));
    const rest = g.entries.length - shown.length;
    if (rest > 0) shown.push(`[+${rest} more](${base}#${groupAnchor(g.id)})`);
    return `| [${g.label}](${base}#${groupAnchor(g.id)}) | ${g.entries.length} | ${shown.join(" · ")} |`;
  });
  return ["| Category | Count | Entries |", "|---|---:|---|", ...rows].join("\n");
}

function coverageMatrix(catalog) {
  const head = `| Protocol | Category | ${KINDS.join(" | ")} |`;
  const sep = `|---|---|${KINDS.map(() => ":-:").join("|")}|`;
  const rows = grouped(catalog).flatMap(g =>
    g.entries.map(e => `| ${link(e)} | ${g.label} | ${KINDS.map(k => mark(e.kinds[k])).join(" | ")} |`)
  );
  return [head, sep, ...rows].join("\n");
}

function renderDoc(catalog) {
  const out = [
    "# Protocol catalog",
    "",
    "<!-- Generated by `npm run catalog:docs` from src/catalog/protocols.js + package.json. Do not edit by hand. -->",
    "",
    `${catalog.protocols.length} protocols and ${catalog.boards.length} cross-protocol boards/tools, ${totalScripts(catalog)} npm scripts. ` +
      "In a terminal, `npm run catalog` prints the same view and `npm run catalog -- <protocol>` prints one card.",
    "",
    "**Kinds:** *Analytics* prints a live snapshot. *Smoke* is a pass/fail check of the same data source (exit code ≠ 0 when it breaks). " +
      "*Simulate* quotes or replays on-chain (RPC or fork). *Swap* is a wallet-backed example. *Cross-chain* aggregates one protocol across chains (subgraphs).",
    "",
    "## Index",
    "",
    categoryIndex(catalog),
    "",
    "## Coverage matrix",
    "",
    coverageMatrix(catalog),
    "",
  ];
  for (const g of allGroups(catalog)) {
    out.push(`<a id="${groupAnchor(g.id)}"></a>`, "", `## ${g.label}`, "");
    for (const e of g.entries) out.push(card(e, 3));
  }
  return (
    out
      .join("\n")
      .replace(/\n{3,}/g, "\n\n")
      .trimEnd() + "\n"
  );
}

function renderReadmeSection(catalog) {
  return [
    README_START,
    "",
    `**${catalog.protocols.length} protocols**, **${catalog.boards.length} cross-protocol boards/tools**, **${totalScripts(catalog)} commands** (not counting repo tooling such as lint and reports). ` +
      `Each name links to its card in the [protocol catalog](${DOC_PATH}): every command, what it prints, and what it needs.`,
    "",
    categoryIndex(catalog, DOC_PATH, README_PREVIEW),
    "",
    README_END,
  ].join("\n");
}

function replaceReadmeSection(readme, catalog) {
  const start = readme.indexOf(README_START);
  const end = readme.indexOf(README_END);
  if (start === -1 || end === -1) throw new Error(`README is missing ${README_START} / ${README_END} markers`);
  return readme.slice(0, start) + renderReadmeSection(catalog) + readme.slice(end + README_END.length);
}

module.exports = { DOC_PATH, renderDoc, replaceReadmeSection };
